---
openapi: 3.0.1
info:
  title: api
  version: ""
paths:
  /v1/balance/:
    get:
      description: Get account balance in cents
      operationId: balance_getBalance
      tags:
        - Balance
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
        "404":
          description: ""
      security:
        - BearerAuth: []
  /v1/health/:
    get:
      operationId: health_getHealth
      tags:
        - Health
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
      summary: Get health status
  /v1/link/extract:
    post:
      operationId: link_extract
      tags:
        - Link
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Extract download link from a given URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkRequest'
  /v1/link/sites:
    get:
      operationId: link_get-supported-sites
      tags:
        - Link
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
      summary: Get supported sites
  /v1/transcriptions/:
    post:
      description: Create a new transcription
      operationId: transcribe_createTranscription
      tags:
        - Transcribe
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscriptionId'
        "401":
          description: ""
        "429":
          description: ""
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranscriptionRequest'
  /v1/transcriptions/{transcription_id}/status:
    get:
      description: Get transcription status
      operationId: transcribe_getTranscriptionStatus
      tags:
        - Transcribe
      parameters:
        - name: transcription_id
          in: path
          description: ID of the transcription
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscriptionInfo'
        "401":
          description: ""
        "404":
          description: ""
        "429":
          description: ""
      security:
        - BearerAuth: []
  /v1/transcriptions/{transcription_id}:
    get:
      description: Get transcription
      operationId: transcribe_getTranscription
      tags:
        - Transcribe
      parameters:
        - name: transcription_id
          in: path
          description: ID of the transcription
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transcription'
        "401":
          description: ""
        "404":
          description: ""
        "429":
          description: ""
      security:
        - BearerAuth: []
components:
  schemas:
    Balance:
      title: Balance
      type: object
      properties:
        cents_remaining:
          type: integer
          description: The amount remaining in the billing account associated with the API user, represented in cents.
      required:
        - cents_remaining
    HealthResponse:
      title: HealthResponse
      type: object
      properties:
        status:
          type: string
          description: Health status
      required:
        - status
    LinkRequest:
      title: LinkRequest
      type: object
      properties:
        url:
          type: string
          description: URL to extract the download link from. Must be from a supported site.
      required:
        - url
    LinkResponse:
      title: LinkResponse
      type: object
      properties:
        title:
          type: string
          description: Title of the file
        download_url:
          type: string
          description: Download URL of the file
        file_format:
          type: string
          description: Format of the file
        file_name:
          type: string
          description: Name of the file
      required:
        - title
        - download_url
        - file_format
        - file_name
    Site:
      title: Site
      type: object
      properties:
        name:
          type: string
          description: Name of the site
        url:
          type: string
          description: URL of the site
      required:
        - name
        - url
    TranscriptionRequest:
      title: TranscriptionRequest
      type: object
      properties:
        audio_url:
          type: string
          nullable: true
          description: URL to a downloadable audio file. Must be a direct link to the file (not a streaming or preview link). If the URL is not directly downloadable, consider using our Link API to extract a downloadable link from supported sites. Either audio_url or audio_file must be provided, but not both.
        audio_file:
          type: string
          nullable: true
          description: Base64 encoded audio file content. Either audio_url or audio_file must be provided, but not both.
        info:
          $ref: '#/components/schemas/TranscriptionRequestInfo'
          description: Transcription parameters
      required:
        - info
    Language:
      title: Language
      type: string
      enum:
        - en
        - he
        - yi
    LettersLanguage:
      title: LettersLanguage
      type: string
      enum:
        - en
        - he
    TranscriptionId:
      title: TranscriptionId
      type: string
      format: uuid
      description: ID of the transcription
    Status:
      title: Status
      type: string
      enum:
        - RECEIVED
        - PENDING
        - PROCESSING
        - COMPLETED
        - CANCELLED
        - FAILED
    TranscriptionRequestInfo:
      title: TranscriptionRequestInfo
      type: object
      properties:
        model:
          type: string
          nullable: true
          description: |-
            Model to be used for the transcription. Default is "v1".
            - v1: Our latest and most accurate model, especially for audio with longer stretches of Hebrew.
            Priced at 1.50 USD per hour of audio transcribed.
            - v0: Suitable for audio with fewer Hebrew words.
            Priced at 1.00 USD per hour.
        id:
          $ref: '#/components/schemas/TranscriptionId'
          nullable: true
          description: ID of the transcription. If passed, it will be set as the ID. If not, a UUID will be generated.
        title:
          type: string
          nullable: true
          description: Title for the transcription, Default is "Untitled"
        primary_language:
          $ref: '#/components/schemas/Language'
          nullable: true
          description: |-
            Specifies the primary language spoken in the audio content. Default is English.
            - en: English
            - he: Hebrew
            - yi: Yiddish
        hebrew_word_format:
          type: array
          items:
            $ref: '#/components/schemas/LettersLanguage'
          nullable: true
          description: |-
            Relevant only if the primary language is English. This setting determines how non-English word, are formatted in the transcription.
            - To include Hebrew words in their original Hebrew letters, specify "he".
            - To transliterate Hebrew words into English letters, specify "en".
            - If both "he" and "en" are specified, each Hebrew word will be provided in both formats, with the transliteration in <i> tags.
            - If the primary language is English, the default is to include both English transliteration and original Hebrew letters ("en" and "he").
            - If the primary language is not English, the default and only option is to include Hebrew words in their original Hebrew letters ("he").
        num_speakers:
          type: integer
          nullable: true
          description: Expected number of speakers in the audio. Default is 1. If a number more than 1 is passed, it will be used for speaker labeling (a pro feature).
    TranscriptionInfo:
      title: TranscriptionInfo
      type: object
      properties:
        id:
          $ref: '#/components/schemas/TranscriptionId'
          description: ID of the transcription
        title:
          type: string
          description: Title of the transcription
        created_at:
          type: string
          format: date-time
          description: When the transcription was created
        primary_language:
          $ref: '#/components/schemas/Language'
          description: The primary language of the audio content, which can be English (en), Hebrew (he), or Yiddish (yi).
        hebrew_word_format:
          type: array
          items:
            $ref: '#/components/schemas/LettersLanguage'
          description: |-
            Indicates how Hebrew words are transcribed in the response when the primary language is English.
            - Hebrew words are in Hebrew letters if "he" is specified.
            - Hebrew words are transliterated into English letters if "en" is specified.
            - If both "he" and "en" are specified, both versions are provided back-to-back for each Hebrew word.
            Transliterated Hebrew words are surrounded by <i> tags in the response text.
        num_speakers:
          type: integer
          description: Number of speakers in the audio. If more than 1, then speaker labeling is enabled (a pro feature).
        status:
          $ref: '#/components/schemas/Status'
          description: Current status of the transcription
        duration:
          type: integer
          format: float
          description: Duration of the audio in seconds
        model:
          type: string
          nullable: true
          description: Model used for the transcription. V1 is the latest and most accurate model, especially for audio with longer stretches of Hebrew. V0 is suitable for audio with fewer Hebrew words.
      required:
        - id
        - title
        - created_at
        - primary_language
        - hebrew_word_format
        - num_speakers
        - status
        - duration
    Transcription:
      title: Transcription
      type: object
      properties:
        text:
          type: string
          description: This field contains the transcription text. If the `primary_language` is English and only one `hebrew_word_format` is specified, the text will be in English with Hebrew words in the specified format. If multiple `hebrew_word_format` options are set, Hebrew words will appear in both formats, with the English transliteration in <i>Italics</i>. If the primary language is Hebrew, the text will be in Hebrew.
        timestamps:
          type: array
          items:
            $ref: '#/components/schemas/Timestamp'
          nullable: true
          description: Timestamps object for the transcription. See the `timestamps` object for more details.
        info:
          $ref: '#/components/schemas/TranscriptionInfo'
          description: Additional information about the transcription
      required:
        - text
        - info
    Timestamp:
      title: Timestamp
      type: object
      properties:
        word:
          type: string
          description: Word
        hebrew_word_format:
          type: array
          items:
            $ref: '#/components/schemas/LettersLanguage'
          nullable: true
          description: Specifies the format of Hebrew words in the transcription. Hebrew words are denoted as "he" for Hebrew letters or "en" for English transliteration. Non-Hebrew words are represented by null.
        start:
          type: number
          format: double
          description: Start time of the timestamp
        end:
          type: number
          format: double
          description: End time of the timestamp
        speaker:
          type: string
          nullable: true
          description: If speaker labeling was requested, indicates which speaker number spoke this word (Pro feature)
      required:
        - word
        - start
        - end
    UpdateTimestampsRequest:
      title: UpdateTimestampsRequest
      type: object
      properties:
        old_timestamps:
          type: array
          items:
            $ref: '#/components/schemas/Timestamp'
          description: The original timestamps associated with the text before editing. These will be used as reference points to align the new timestamps.
        edited_text:
          type: string
          description: The modified version of the transcription text that needs updated timestamp alignments. This should be the complete text after your edits.
        language_to_update:
          $ref: '#/components/schemas/Language'
          description: Specifies which language version of the timestamps to update. Must be either 'en' for English or 'he' for Hebrew timestamps.
      required:
        - old_timestamps
        - edited_text
        - language_to_update
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
servers:
  - url: https://api.sofer.ai
    description: Production
  - url: https://api-staging.sofer.ai
    description: Staging
  - url: http://localhost:8001
    description: Development
